export interface Producto{
id:	number,
brand: string,
name: string,
price: string,
price_sign:	string,
currency: string,
image_link: string,
product_link: string,
website_link: string,
description: string,
rating:	string,
category: string,
product_type: string,
product_api_url: string,
api_featured_image: string,
}